## Numpy Library Exercise

In [22]:
import numpy as np
# We keep this seed to make the results reproducible.
np.random.seed(67)
arr = np.random.randint(-10, 10, 20)
print(arr)

[-7  0 -5 -3 -1 -7  3 -7 -2 -7 -6  4  3 -9  0  9 -3 -8 -1 -7]


1. Given a random array, change the sign of elements whose values are between 3 and 8

In [23]:
q1 = np.where((arr > 3) & (arr < 8), -arr, arr)
print(q1)

[-7  0 -5 -3 -1 -7  3 -7 -2 -7 -6 -4  3 -9  0  9 -3 -8 -1 -7]


2. Replace the maximum element of a random array with 0

In [24]:
q2 = np.where(arr == arr.max(), 0, arr)
print(q2)

[-7  0 -5 -3 -1 -7  3 -7 -2 -7 -6  4  3 -9  0  0 -3 -8 -1 -7]


3. Construct the Cartesian product of arrays (all combinations with each element). A two-dimensional array is given as input.


In [25]:
arr_2dim = np.array([[1, 2, 3], [4, 5, 6]])
a, b = arr_2dim[0], arr_2dim[1]
a, b = np.meshgrid(a, b, indexing="ij")
q3 = np.column_stack([a.ravel(), b.ravel()])
print(q3)

[[1 4]
 [1 5]
 [1 6]
 [2 4]
 [2 5]
 [2 6]
 [3 4]
 [3 5]
 [3 6]]


4. Given 2 arrays A (8x3) and B (2x2). Find rows in A that contain elements from each row in B, regardless of the order of elements in B

In [26]:
A = np.random.randint(0, 10, (8, 3))
B = np.random.randint(0, 10, (2, 2))
print(A, B, sep="\n\n")
q4 = A[np.all(np.isin(A, B), axis=1)]
print(q4)

[[2 6 9]
 [6 4 8]
 [3 1 4]
 [8 2 7]
 [0 7 7]
 [5 2 0]
 [7 3 5]
 [9 1 6]]

[[1 3]
 [4 5]]
[[3 1 4]]


5. Given a 10x3 matrix, find rows with unequal values (e.g., row [2,2,3] remains, row [3,3,3] is removed)

In [27]:
A = np.random.randint(0, 10, (10, 3))
print(A)
A[2] = [2, 2, 2]
q5 = A[~np.all(A[:, 1:] == A[:, :-1], axis=1)]
print(q5)

[[0 8 5]
 [9 5 2]
 [8 7 6]
 [3 4 9]
 [1 4 8]
 [0 7 7]
 [1 8 0]
 [8 4 5]
 [0 4 8]
 [9 2 5]]
[[0 8 5]
 [9 5 2]
 [3 4 9]
 [1 4 8]
 [0 7 7]
 [1 8 0]
 [8 4 5]
 [0 4 8]
 [9 2 5]]


6. Given a two-dimensional array. Remove duplicate rows

In [28]:
A = np.random.randint(0, 10, (4, 4))
A[0] = A[1]
print(A)
q6 = np.unique(A, axis=0)
print(q6)

[[5 1 6 6]
 [5 1 6 6]
 [0 9 9 4]
 [4 3 4 0]]
[[0 9 9 4]
 [4 3 4 0]
 [5 1 6 6]]


______
______

For each of the following tasks (1-5), you need to provide 2 implementations – one without using numpy (assume that where numpy arrays should be on input or output, there will simply be lists), and the second fully vectorized using numpy (without using Python loops/map/list comprehensions).

Remark 1. It can be assumed that all specified objects are non-empty (for example, in task 1, there are non-zero elements on the diagonal of the matrix).

Remark 2. For most tasks, the solution takes no more than 1-2 lines.

___

Task 1: Calculate the product of non-zero elements on the diagonal of a rectangular matrix. For example, for:
```
X = np.array([
  [1, 0, 1],
  [2, 0, 2],
  [3, 0, 3],
  [4, 4, 4]
  ])
```
the answer is 3.

In [29]:
import math
X = [
  [1, 0, 1],
  [2, 0, 2],
  [3, 0, 3],
  [4, 4, 4]
  ]
res = math.prod([X[i][i] for i in range(min(len(X), len(X[0]))) if X[i][i] != 0])
print(res)

X = np.array(X)
res = np.prod(np.diagonal(X)[np.diagonal(X) != 0])
print(res)

3
3


Task 2: Given two vectors x and y. Check if they represent the same multiset. For example, for x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2])


In [30]:
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
print(sorted(x) == sorted(y))
x = np.array(x)
y = np.array(y)
print(np.array_equal(np.sort(x), np.sort(y)))

True
True


Task 3: Find the maximum element in vector x among elements preceded by zero. For example, for x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) the answer is 5.

In [31]:
ans = -float('inf')
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
ans = max(x[i] for i in range(1, len(x)) if x[i-1]==0)
print(ans)

x = np.array(x)
ans = np.max(x[1:][x[:-1] == 0])
print(ans)

5
5


Task 4: Implement Run-length encoding. For a given vector x, return a tuple of two vectors of the same length. The first contains the numbers, and the second - how many times they should be repeated. For example, for x = np.array([2, 2, 2, 3, 3, 3, 5]) the answer is (np.array([2, 3, 5]), np.array([3, 3, 1]))

In [32]:
from collections import Counter
x = [2, 2, 2, 3, 3, 3, 5]
counter = Counter(x)
a, b = list(counter.keys()), list(counter.values())
print((a, b))

x = np.array(x)
a, b = np.unique(x), np.array([np.count_nonzero(x == i) for i in a])
print((a, b))


([2, 3, 5], [3, 3, 1])
(array([2, 3, 5]), array([3, 3, 1]))


Task 5: Given two samples of objects - X and Y. Calculate the matrix of Euclidean distances between objects.

Compare with the function `scipy.spatial.distance.cdist` in terms of speed.

In [33]:
X = [1, 2, 3]
Y = [4, 5, 6]
dist = sum((x-y)**2 for x, y in zip(X, Y))**(0.5)
print(dist)

X = np.array(X)
Y = np.array(Y)
dist = np.linalg.norm(X - Y)
print(dist)

from scipy.spatial.distance import cdist
dist = cdist(X.reshape(1, -1), Y.reshape(1, -1))
print(dist)

5.196152422706632
5.196152422706632
[[5.19615242]]


_______
________

#### Task 6: CrunchieMunchies

You work in the marketing department of the food company MyCrunch, which is developing a new type of delicious, healthy cereal called CrunchieMunchies.

You want to show consumers how healthy your cereal is compared to other leading brands, so you've collected nutritional data on several different competitors.

Your task is to use Numpy calculations to analyze this data and prove that your CrunchieMunchies are the healthiest choice for consumers.

In [34]:
import numpy as np

1. Review the cereal.csv file. This file contains calorie counts for various cereal brands. Load the data from the file and save it as calorie_stats.

In [35]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. One serving of CrunchieMunchies contains 60 calories. How much higher is the average calorie count of your competitors?

Save the answer in the average_calories variable and print the variable to the terminal.

In [36]:
serving = 60
average_calories = np.average(calorie_stats)
print(average_calories - serving)

46.883116883116884


3. Does the average calorie count accurately reflect the distribution of the dataset? Let's sort the data and see.

Sort the data and save the result in the calorie_stats_sorted variable. Print the sorted information

In [37]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. It seems that most values are above average. Let's see if the median is the most accurate indicator of the dataset.

Calculate the median of the dataset and save your answer in median_calories. Print the median so you can see how it compares to the mean.

In [38]:
median_calories = np.median(calorie_stats)
print(median_calories)

110.0


5. While the median shows that at least half of our values are over 100 calories, it would be more impressive to show that a significant portion of competitors have a higher calorie count than CrunchieMunchies.

Calculate different percentiles and print them until you find the smallest percentile that exceeds 60 calories. Save this value in the nth_percentile variable.

In [39]:
percentiles = list(i/10 for i in range(0, 1000))
nth_percentile: float = -float("inf")
for i in percentiles:
    if np.percentile(calorie_stats, i) > 60:
      nth_percentile = i
      break
print(nth_percentile)

3.3


6. Although the percentile shows us that most competitors have a much higher calorie count, this is an inconvenient concept to use in marketing materials.

Instead, let's calculate the percentage of cereals that contain more than 60 calories per serving. Save your answer in the more_calories variable and print it.

In [40]:
print(100 - nth_percentile)

96.7


7. This is indeed a high percentage. This will be very useful when we promote CrunchieMunchies. But one question is, how significant are the differences in the dataset? Can we generalize that most cereals contain around 100 calories, or is the spread even greater?

Calculate the magnitude of deviation by finding the standard deviation. Save your answer in calorie_std and print it to the terminal. How can we incorporate this value into our analysis?

In [41]:
calorie_std = np.std(calorie_stats)
print(calorie_std)
# We can construct the significance interval
one_std_interval = (average_calories - calorie_std, average_calories + calorie_std)
two_std_interval = (average_calories - 2*calorie_std, average_calories + 2*calorie_std)
print(f"68% values lies in the interval: ({one_std_interval[0]:.2f}, {one_std_interval[1]:.2f})")
print(f"95% values lies in the interval: ({two_std_interval[0]:.2f}, {two_std_interval[1]:.2f})")
# We can deduce that CrunchieMunchie cookies are in the 2.1% of distribution.


19.35718533390827
68% values lies in the interval: (87.53, 126.24)
95% values lies in the interval: (68.17, 145.60)


8. Write a short paragraph briefly summarizing your findings and how, in your opinion, this data can be used to benefit Mycrunch in marketing CrunchieMunchies

In [42]:
# The analysis proved, that CrunchieMunchies are the better less caloric option.
# 95% of cereal lie in the interval (68, 146), thanks to the 3sigma rule tells
# us our cereal are in the 2.1% of caloric distribution.